// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfAJOOdmbUnOOBvsfiKG5q8azRl3DkQlg',
    appId: '1:896424627329:web:4c0b8713869d3c39d59180',
    messagingSenderId: '896424627329',
    projectId: 'chatapp-197f7',
    authDomain: 'chatapp-197f7.firebaseapp.com',
    storageBucket: 'chatapp-197f7.appspot.com',
    measurementId: 'G-E5LP96R3QN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOo5sMZF29kPiQnd-ODkI5VjzS6pXxGBE',
    appId: '1:896424627329:android:652c06609465dd35d59180',
    messagingSenderId: '896424627329',
    projectId: 'chatapp-197f7',
    storageBucket: 'chatapp-197f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0dsJ3Lnf_vzaCb-2beAjQyL-51Xji89c',
    appId: '1:896424627329:ios:d25519ebf764c41dd59180',
    messagingSenderId: '896424627329',
    projectId: 'chatapp-197f7',
    storageBucket: 'chatapp-197f7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
